In [9]:
import pandas as pd
import glob

vgobjdf = pd.read_json('./PreprocOut/vgobjdf.json.gz', compression='gzip', orient='split')
vgregdf = pd.read_json('./PreprocOut/vgregdf.json.gz', compression='gzip', orient='split')
vgreldf = pd.read_json('./PreprocOut/vgreldf.json.gz', compression='gzip', orient='split')
vgattdf = pd.read_json('./PreprocOut/vgattdf.json.gz', compression='gzip', orient='split')
vgimgdf = pd.read_json('./PreprocOut/vgimgdf.json.gz', compression='gzip', orient='split')

In [36]:
with open('../ExtractFeats/bw_vg_images.txt', 'r') as f4:
    bw = f4.read().split('\n')
bw = [int(item) for item in bw if item != '']
with open('../ExtractFeats/negbb_vg_images.txt', 'r') as f5:
    negbb = f5.read().split('\n')
negbb = [int(item) for item in negbb if item != '']

In [49]:
def fix_df(input_df):
    interm_df = input_df[~input_df.image_id.isin(bw)]
    im_df = interm_df[~interm_df.image_id.isin(negbb)]
    return im_df

In [53]:
new_vgobjdf = fix_df(vgobjdf)
new_vgregdf = fix_df(vgregdf)
new_vgreldf = fix_df(vgreldf)
new_vgattdf = fix_df(vgattdf)
new_vgimgdf = fix_df(vgimgdf)

In [58]:
new_vgimgdf['image_id'].unique().shape

(107957,)

In [61]:
new_vgobjdf.to_json('./PreprocOut/vgobjdf_filtered.json.gz', compression='gzip', orient='split')

In [62]:
import pandas as pd
vgobjdf = pd.read_json('./PreprocOut/vgobjdf_filtered.json.gz', compression='gzip', orient='split')

In [63]:
vgobjdf['image_id'].unique().shape

(106164,)

In [80]:
interm_df = vgobjdf.groupby('image_id').count()
interm_df.loc[interm_df['i_corpus'].idxmax()]

i_corpus    150
obj_id      150
syn         149
name        150
bb          150
Name: 2337434, dtype: int64

In [82]:
vgobjdf[vgobjdf['image_id'] == 2337434]

,i_corpus,image_id,obj_id,syn,name,bb
1927505,5,2337434,957663,card.n.01,card,"[1, 1, 341, 497]"
1927506,5,2337434,957716,rotter.n.01,crumb,"[16, 461, 8, 3]"
1927507,5,2337434,957718,rotter.n.01,crumb,"[107, 453, 3, 3]"
1927508,5,2337434,957720,rotter.n.01,crumb,"[55, 413, 3, 3]"
1927509,5,2337434,957722,rotter.n.01,crumb,"[46, 417, 3, 3]"
1927510,5,2337434,957724,rotter.n.01,crumb,"[48, 396, 3, 2]"
1927511,5,2337434,957686,flower.n.01,flower,"[234, 135, 14, 18]"
1927512,5,2337434,957611,flower.n.01,flower,"[73, 81, 21, 19]"
1927513,5,2337434,957690,flower.n.01,flower,"[218, 161, 21, 16]"
1927514,5,2337434,957619,flower.n.01,flower,"[114, 122, 19, 18]"
1927515,5,2337434,957691,flower.n.01,flower,"[183, 173, 17, 16]"
1927516,5,2337434,957621,flower.n.01,flower,"[114, 142, 28, 20]"
1927517,5,2337434,957692,flower.n.01,flower,"[224, 177, 13, 17]"
1927518,5,2337434,957623,flower.n.01,flower,"[120, 170, 20, 25]"
1927519,5,2337434,957693,flower.n.01,flower,"[234, 179, 26, 23]"
1927520,5,2337434,957625,flower.n.01,flower,"[152, 95, 14, 12]"
1927521,5,2337434,957694,flower.n.01,flower,"[221, 187, 16, 20]"
1927522,5,2337434,957627,flower.n.01,flower,"[161, 103, 12, 16]"
1927523,5,2337434,957695,flower.n.01,flower,"[198, 183, 20, 23]"
1927524,5,2337434,957629,flower.n.01,flower,"[172, 101, 19, 18]"
1927525,5,2337434,957696,flower.n.01,flower,"[147, 153, 18, 15]"
1927526,5,2337434,957631,flower.n.01,flower,"[155, 131, 19, 12]"
1927527,5,2337434,957697,flower.n.01,flower,"[167, 197, 18, 21]"
1927528,5,2337434,957633,flower.n.01,flower,"[207, 85, 19, 23]"
1927529,5,2337434,957698,flower.n.01,flower,"[157, 172, 14, 20]"
1927530,5,2337434,957635,flower.n.01,flower,"[207, 106, 21, 17]"
1927531,5,2337434,957699,flower.n.01,flower,"[191, 198, 17, 17]"
1927532,5,2337434,957637,flower.n.01,flower,"[189, 131, 22, 27]"
1927533,5,2337434,957700,flower.n.01,flower,"[229, 205, 19, 17]"
1927534,5,2337434,957639,flower.n.01,flower,"[159, 140, 22, 18]"
...,...,...,...,...,...,...
1927625,5,2337434,957745,flower_bud.n.01,flower bud,"[313, 114, 10, 10]"
1927626,5,2337434,957744,flower_bud.n.01,flower bud,"[324, 108, 5, 5]"
1927627,5,2337434,957704,handle.n.01,handle,"[228, 272, 48, 141]"
1927628,5,2337434,957732,heart.n.01,heart,"[212, 11, 15, 14]"
1927629,5,2337434,957749,letter.n.01,letter,"[43, 416, 52, 47]"
1927630,5,2337434,957748,letter.n.01,letter,"[7, 424, 44, 58]"
1927631,5,2337434,957742,inscription.n.01,lettering,"[14, 6, 191, 20]"
1927632,5,2337434,957743,inscription.n.01,lettering,"[84, 28, 188, 15]"
1927633,5,2337434,957662,None,love message,"[14, 7, 258, 36]"
1927634,5,2337434,957616,chump.n.01,mug,"[128, 244, 150, 216]"
1927635,5,2337434,957741,contemplation.n.02,reflection,"[141, 473, 185, 25]"
1927636,5,2337434,957708,root.n.01,root,"[178, 305, 13, 70]"
1927637,5,2337434,957710,root.n.01,root,"[183, 304, 41, 42]"
1927638,5,2337434,957712,root.n.01,root,"[185, 304, 16, 42]"
1927639,5,2337434,957706,root.n.01,root,"[169, 307, 7, 65]"
1927640,5,2337434,957733,shadow.n.01,shadow,"[257, 132, 87, 159]"
1927641,5,2337434,957761,root.n.03,stem,"[81, 81, 58, 96]"
1927642,5,2337434,957756,root.n.03,stem,"[174, 95, 23, 129]"
1927643,5,2337434,957757,root.n.03,stem,"[268, 113, 39, 60]"
1927644,5,2337434,957759,root.n.03,stem,"[81, 144, 73, 47]"
1927645,5,2337434,957731,table.n.02,table,"[0, 379, 343, 120]"
1927646,5,2337434,957734,wall.n.01,wall,"[1, 1, 342, 394]"
1927647,5,2337434,957715,water.n.01,water,"[129, 290, 103, 135]"
1927648,5,2337434,957740,water_line.n.02,watermark,"[6, 415, 88, 65]"
1927649,5,2337434,957755,word.n.01,word,"[246, 33, 25, 10]"
1927650,5,2337434,957751,word.n.01,word,"[125, 29, 40, 14]"
1927651,5,2337434,957752,word.n.01,word,"[167, 29, 28, 13]"
1927652,5,2337434,957753,word.n.01,word,"[198, 29, 28, 14]"
1927653,5,2337434,957754,word.n.01,word,"[230, 34, 15, 8]"
1927654,5,2337434,957750,word.n.01,word,"[85, 29, 36, 14]"

In [65]:
# clean vgobgdf

# 1. 50 obj per image
# 2. remove objects, which do not have bounding boxes (0,0,0,0)
# 3. remove objects, which cover full image
# 4. remove object with repetitive descriptions if there are more than 50
# 5. pad zeros if there are less than 50 regions

In [ ]:
zero_bbs = {}
wh_bbs = {}

for num, row in vgobjdf.iterrows():
    image_id = row.image_id
    zero_bbs[image_id] = []
    wh_bbs[image_id] = []
    w = vgimgdf[vgimgdf.image_id == image_id]['width'].item()
    h = vgimgdf[vgimgdf.image_id == image_id]['height'].item()
    if row.bb == [0, 0, 0, 0]:
        zero_bbs[image_id].append(row.obj_id)
    elif row.bb == [0, 0, w, h]:
        wh_bbs[image_id].append(row.obj_id)

In [ ]:
vgattdf.head()

In [ ]:
vgimgdf.head()